server:
  port: 8080
  ssl:
    enabled: false

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://119.192.227.70:9999/trace_price_dev?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=20480
    username: root
    password: akfldk2!
  security:
    user:
      name: test
      password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update #create-drop
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

python:
  api:
    server: http://localhost:5000